title: Janith's
description: A technocrat's journey through code, ideas, and digital innovation
baseurl: ""
url: "https://janithkv.github.io"
github_username: janithkv

markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap

# GitHub Pages specific
theme: minima

collections:
  apps:
    output: true
    permalink: /apps/:name/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "apps"
    values:
      layout: "app"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/